services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}                    #referencing .env file for these variables
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Mount volume to pgdata/
      - ./data:/app/data                   # Mount the data folder containing CSV files

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}             #again referencing .env file
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"  # Expose pgAdmin on port 5050
    depends_on:
      - db  # pgAdmin starts after the db container

  api-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./app:/inventory-backend/app
 
