[project]
name = "inventory-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pandas>=2.2.3",
    "psycopg>=3.2.9",
    "uvicorn[standard]>=0.34.2",
]
